const ADD_TAB = "ADD_TAB";
const CHANGE_ACTIVE_TAB = "CHANGE_ACTIVE_TAB";
const REMOVE_TAB = "REMOVE_TAB";
const REMOVE_TAB_DELAYED = "REMOVE_TAB_DELAYED";

export { ADD_TAB, CHANGE_ACTIVE_TAB, REMOVE_TAB, REMOVE_TAB_DELAYED };
