const ADD_TAB = "ADD_TAB";
const CHANGE_TAB_CONTENT = "CHANGE_TAB_CONTENT";
const CHANGE_ACTIVE_TAB = "CHANGE_ACTIVE_TAB";
const REMOVE_TAB = "REMOVE_TAB";
const REMOVE_TAB_DELAYED = "REMOVE_TAB_DELAYED";

export {
  ADD_TAB,
  CHANGE_TAB_CONTENT,
  CHANGE_ACTIVE_TAB,
  REMOVE_TAB,
  REMOVE_TAB_DELAYED
};
