version: "3.7"

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.7.2
    restart: always
    environment:
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    networks:
      esnet:
        ipv4_address: 172.18.18.3

  manerapedia-middleware:
    build: ./middleware
    restart: always
    ports:
      - 5000:5000
    networks:
      esnet:
        ipv4_address: 172.18.18.2

networks:
  esnet:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
    ipam:
      driver: default
      config:
        - subnet: 172.18.18.0/24
