const AUTOCOMPLETE_REQUEST = "AUTOCOMPLETE_REQUEST";
const AUTOCOMPLETE_SUCCESS = "AUTOCOMPLETE_SUCCESS";
const AUTOCOMPLETE_FAILURE = "AUTOCOMPLETE_FAILURE";

export { AUTOCOMPLETE_REQUEST, AUTOCOMPLETE_SUCCESS, AUTOCOMPLETE_FAILURE };
