const AUTOCOMPLETE_REQUEST = "AUTOCOMPLETE_REQUEST";
const AUTOCOMPLETE_SUCCESS = "AUTOCOMPLETE_SUCCESS";
const AUTOCOMPLETE_FAILURE = "AUTOCOMPLETE_FAILURE";
const GET_ARTICLE_REQUEST = "GET_ARTICLE_REQUEST";
const GET_ARTICLE_SUCCESS = "GET_ARTICLE_SUCCESS";
const GET_ARTICLE_FAILURE = "GET_ARTICLE_FAILURE";
const SEARCH_REQUEST = "SEARCH_REQUEST";
const SEARCH_REQUEST_SUCCESS = "SEARCH_REQUEST_SUCCESS";
const SEARCH_REQUEST_FAILURE = "SEARCH_REQUEST_FAILURE";

export {
  AUTOCOMPLETE_REQUEST,
  AUTOCOMPLETE_SUCCESS,
  AUTOCOMPLETE_FAILURE,
  GET_ARTICLE_REQUEST,
  GET_ARTICLE_SUCCESS,
  GET_ARTICLE_FAILURE,
  SEARCH_REQUEST,
  SEARCH_REQUEST_SUCCESS,
  SEARCH_REQUEST_FAILURE
};
